# Generated by Django 2.0 on 2017-12-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
